name: Testing secret variables

on:
  workflow_dispatch
env:
     ACTIONS_STEP_DEBUG: true
jobs: 
   test_context_variables:
     runs-on: ubuntu-latest
     steps: 
       - name: "Checking secret variable"
         run: |
           echo "Secret Value : ${{ secrets.MY_KEY }}"
           ${{ secrets.MY_KEY }}
